CAF-3671: Updated to remap fields  reguardless of encoding
caf-archive/worker-policy pull request #13
Opened 2017-10-30 14:34 UTC by Anthony-McGreevy

2017-10-30 17:09 UTC, mmaBel requested changes

2017-10-30 17:09 UTC, mmaBel commented on handlers-converters/handlers/field-mapping/src/main/java/com/github/cafdataprocessing/worker/policy/handlers/fieldmapping/FieldMappingHandler.java
> +        fieldNameMappings.keySet()
Use CaseInsensitiveKeyMultimap here similar to metadata usage.

2017-10-30 17:09 UTC, mmaBel commented on handlers-converters/handlers/field-mapping/src/test/java/com/github/cafdataprocessing/worker/policy/handlers/fieldmapping/FieldMappingHandlerTest.java
> +        Assert.assertTrue(document.getStreams().containsKey("wrx"));
Check for value here.

2017-10-30 17:56 UTC, Anthony-McGreevy commented
@mmaBel PR updated to reflect review comments.

2017-10-31 09:48 UTC, mmaBel approved these changes

2017-10-31 09:48 UTC, mmaBel commented on handlers-converters/handlers/field-mapping/src/test/java/com/github/cafdataprocessing/worker/policy/handlers/fieldmapping/FieldMappingHandlerTest.java
> +            document.getStreams().put("abc", stream);
The try with isn't needed here. Close on a ByteArrayInput stream doesn't do anything.

https://docs.oracle.com/javase/7/docs/api/java/io/ByteArrayInputStream.html

2017-10-31 09:49 UTC, merged